package com.talentica.paymentgateway.service;

import com.talentica.paymentgateway.filter.RequestWrapper;
import jakarta.servlet.http.HttpServletRequest;
import lombok.extern.slf4j.Slf4j;
import org.slf4j.MDC;
import org.springframework.stereotype.Service;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

/**
 * Service for managing request tracking headers and correlation IDs.
 * Provides centralized access to auto-generated tracking values.
 */
@Slf4j
@Service
public class RequestTrackingService {

    /**
     * Get the correlation ID for the current request.
     * This is automatically generated by RequestTrackingFilter.
     */
    public String getCurrentCorrelationId() {
        // First try to get from MDC (most reliable)
        String correlationId = MDC.get("correlationId");
        if (correlationId != null) {
            return correlationId;
        }

        // Fallback: get from request headers
        HttpServletRequest request = getCurrentRequest();
        if (request != null) {
            correlationId = request.getHeader("X-Correlation-ID");
            if (correlationId != null) {
                return correlationId;
            }
        }

        log.warn("No correlation ID found in current request context");
        return "unknown-correlation-id";
    }

    /**
     * Get the idempotency key for the current request.
     * This is automatically generated by RequestTrackingFilter for payment operations.
     */
    public String getCurrentIdempotencyKey() {
        // First try to get from MDC
        String idempotencyKey = MDC.get("idempotencyKey");
        if (idempotencyKey != null) {
            return idempotencyKey;
        }

        // Fallback: get from request headers
        HttpServletRequest request = getCurrentRequest();
        if (request != null) {
            idempotencyKey = request.getHeader("Idempotency-Key");
            if (idempotencyKey != null) {
                return idempotencyKey;
            }
        }

        return null; // Idempotency key is optional for non-payment operations
    }

    /**
     * Check if the current request has an idempotency key.
     */
    public boolean hasIdempotencyKey() {
        return getCurrentIdempotencyKey() != null;
    }

    /**
     * Get the current HTTP request from Spring's RequestContextHolder.
     */
    private HttpServletRequest getCurrentRequest() {
        try {
            ServletRequestAttributes attributes = (ServletRequestAttributes) RequestContextHolder.currentRequestAttributes();
            return attributes.getRequest();
        } catch (IllegalStateException e) {
            log.debug("No request context available: {}", e.getMessage());
            return null;
        }
    }

    /**
     * Log request tracking information for debugging.
     */
    public void logTrackingInfo() {
        String correlationId = getCurrentCorrelationId();
        String idempotencyKey = getCurrentIdempotencyKey();
        
        log.debug("Request tracking - CorrelationId: {}, IdempotencyKey: {}", 
                    correlationId, idempotencyKey);
    }
}
