package com.talentica.paymentgateway.dto.analytics;

import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.List;
import java.util.Map;

/**
 * DTO for compliance reporting including audit trails and regulatory data.
 * Provides comprehensive compliance information for audit and regulatory requirements.
 * 
 * @author Payment Gateway Team
 * @version 1.0.0
 */
@Schema(description = "Compliance report for audit and regulatory requirements")
public class ComplianceReport {
    
    @Schema(description = "Report type (AUDIT, PCI_DSS, GDPR, SOX)")
    private String reportType;
    
    @Schema(description = "Report generation timestamp")
    private ZonedDateTime reportGeneratedAt;
    
    @Schema(description = "Report period start")
    private ZonedDateTime periodStart;
    
    @Schema(description = "Report period end")
    private ZonedDateTime periodEnd;
    
    @Schema(description = "Report generated by")
    private String generatedBy;
    
    @Schema(description = "Compliance status overview")
    private ComplianceStatus complianceStatus;
    
    @Schema(description = "Transaction audit summary")
    private TransactionAuditSummary transactionAudit;
    
    @Schema(description = "Security compliance metrics")
    private SecurityComplianceMetrics securityMetrics;
    
    @Schema(description = "Data privacy compliance")
    private DataPrivacyCompliance dataPrivacy;
    
    @Schema(description = "Operational risk assessments")
    private List<RiskAssessment> riskAssessments;
    
    @Schema(description = "Compliance violations and issues")
    private List<ComplianceViolation> violations;
    
    @Schema(description = "Recommended actions")
    private List<String> recommendations;
    
    @Schema(description = "Supporting documentation links")
    private List<String> supportingDocuments;
    
    // Constructors
    public ComplianceReport() {
        this.reportGeneratedAt = ZonedDateTime.now();
    }
    
    public ComplianceReport(String reportType, ZonedDateTime periodStart, ZonedDateTime periodEnd) {
        this();
        this.reportType = reportType;
        this.periodStart = periodStart;
        this.periodEnd = periodEnd;
    }
    
    // Getters and Setters
    public String getReportType() {
        return reportType;
    }
    
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }
    
    public ZonedDateTime getReportGeneratedAt() {
        return reportGeneratedAt;
    }
    
    public void setReportGeneratedAt(ZonedDateTime reportGeneratedAt) {
        this.reportGeneratedAt = reportGeneratedAt;
    }
    
    public ZonedDateTime getPeriodStart() {
        return periodStart;
    }
    
    public void setPeriodStart(ZonedDateTime periodStart) {
        this.periodStart = periodStart;
    }
    
    public ZonedDateTime getPeriodEnd() {
        return periodEnd;
    }
    
    public void setPeriodEnd(ZonedDateTime periodEnd) {
        this.periodEnd = periodEnd;
    }
    
    public String getGeneratedBy() {
        return generatedBy;
    }
    
    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }
    
    public ComplianceStatus getComplianceStatus() {
        return complianceStatus;
    }
    
    public void setComplianceStatus(ComplianceStatus complianceStatus) {
        this.complianceStatus = complianceStatus;
    }
    
    public TransactionAuditSummary getTransactionAudit() {
        return transactionAudit;
    }
    
    public void setTransactionAudit(TransactionAuditSummary transactionAudit) {
        this.transactionAudit = transactionAudit;
    }
    
    public SecurityComplianceMetrics getSecurityMetrics() {
        return securityMetrics;
    }
    
    public void setSecurityMetrics(SecurityComplianceMetrics securityMetrics) {
        this.securityMetrics = securityMetrics;
    }
    
    public DataPrivacyCompliance getDataPrivacy() {
        return dataPrivacy;
    }
    
    public void setDataPrivacy(DataPrivacyCompliance dataPrivacy) {
        this.dataPrivacy = dataPrivacy;
    }
    
    public List<RiskAssessment> getRiskAssessments() {
        return riskAssessments;
    }
    
    public void setRiskAssessments(List<RiskAssessment> riskAssessments) {
        this.riskAssessments = riskAssessments;
    }
    
    public List<ComplianceViolation> getViolations() {
        return violations;
    }
    
    public void setViolations(List<ComplianceViolation> violations) {
        this.violations = violations;
    }
    
    public List<String> getRecommendations() {
        return recommendations;
    }
    
    public void setRecommendations(List<String> recommendations) {
        this.recommendations = recommendations;
    }
    
    public List<String> getSupportingDocuments() {
        return supportingDocuments;
    }
    
    public void setSupportingDocuments(List<String> supportingDocuments) {
        this.supportingDocuments = supportingDocuments;
    }
    
    /**
     * Overall compliance status.
     */
    @Schema(description = "Overall compliance status and score")
    public static class ComplianceStatus {
        private String overallStatus;
        private double complianceScore;
        private int totalChecks;
        private int passedChecks;
        private int failedChecks;
        private ZonedDateTime lastAuditDate;
        private ZonedDateTime nextAuditDue;
        
        // Constructors
        public ComplianceStatus() {}
        
        // Getters and Setters
        public String getOverallStatus() {
            return overallStatus;
        }
        
        public void setOverallStatus(String overallStatus) {
            this.overallStatus = overallStatus;
        }
        
        public double getComplianceScore() {
            return complianceScore;
        }
        
        public void setComplianceScore(double complianceScore) {
            this.complianceScore = complianceScore;
        }
        
        public int getTotalChecks() {
            return totalChecks;
        }
        
        public void setTotalChecks(int totalChecks) {
            this.totalChecks = totalChecks;
        }
        
        public int getPassedChecks() {
            return passedChecks;
        }
        
        public void setPassedChecks(int passedChecks) {
            this.passedChecks = passedChecks;
        }
        
        public int getFailedChecks() {
            return failedChecks;
        }
        
        public void setFailedChecks(int failedChecks) {
            this.failedChecks = failedChecks;
        }
        
        public ZonedDateTime getLastAuditDate() {
            return lastAuditDate;
        }
        
        public void setLastAuditDate(ZonedDateTime lastAuditDate) {
            this.lastAuditDate = lastAuditDate;
        }
        
        public ZonedDateTime getNextAuditDue() {
            return nextAuditDue;
        }
        
        public void setNextAuditDue(ZonedDateTime nextAuditDue) {
            this.nextAuditDue = nextAuditDue;
        }
    }
    
    /**
     * Transaction audit summary.
     */
    @Schema(description = "Transaction audit trail summary")
    public static class TransactionAuditSummary {
        private long totalTransactions;
        private long auditedTransactions;
        private BigDecimal totalVolume;
        private long anomalousTransactions;
        private Map<String, Long> complianceIssues;
        private double auditCoverage;
        
        // Constructors
        public TransactionAuditSummary() {}
        
        // Getters and Setters
        public long getTotalTransactions() {
            return totalTransactions;
        }
        
        public void setTotalTransactions(long totalTransactions) {
            this.totalTransactions = totalTransactions;
        }
        
        public long getAuditedTransactions() {
            return auditedTransactions;
        }
        
        public void setAuditedTransactions(long auditedTransactions) {
            this.auditedTransactions = auditedTransactions;
        }
        
        public BigDecimal getTotalVolume() {
            return totalVolume;
        }
        
        public void setTotalVolume(BigDecimal totalVolume) {
            this.totalVolume = totalVolume;
        }
        
        public long getAnomalousTransactions() {
            return anomalousTransactions;
        }
        
        public void setAnomalousTransactions(long anomalousTransactions) {
            this.anomalousTransactions = anomalousTransactions;
        }
        
        public Map<String, Long> getComplianceIssues() {
            return complianceIssues;
        }
        
        public void setComplianceIssues(Map<String, Long> complianceIssues) {
            this.complianceIssues = complianceIssues;
        }
        
        public double getAuditCoverage() {
            return auditCoverage;
        }
        
        public void setAuditCoverage(double auditCoverage) {
            this.auditCoverage = auditCoverage;
        }
    }
    
    /**
     * Security compliance metrics.
     */
    @Schema(description = "Security compliance and monitoring metrics")
    public static class SecurityComplianceMetrics {
        private boolean pciDssCompliant;
        private ZonedDateTime lastPciAudit;
        private int securityIncidents;
        private int dataBreaches;
        private double encryptionCoverage;
        private int failedAuthAttempts;
        private Map<String, String> securityControls;
        
        // Constructors
        public SecurityComplianceMetrics() {}
        
        // Getters and Setters
        public boolean isPciDssCompliant() {
            return pciDssCompliant;
        }
        
        public void setPciDssCompliant(boolean pciDssCompliant) {
            this.pciDssCompliant = pciDssCompliant;
        }
        
        public ZonedDateTime getLastPciAudit() {
            return lastPciAudit;
        }
        
        public void setLastPciAudit(ZonedDateTime lastPciAudit) {
            this.lastPciAudit = lastPciAudit;
        }
        
        public int getSecurityIncidents() {
            return securityIncidents;
        }
        
        public void setSecurityIncidents(int securityIncidents) {
            this.securityIncidents = securityIncidents;
        }
        
        public int getDataBreaches() {
            return dataBreaches;
        }
        
        public void setDataBreaches(int dataBreaches) {
            this.dataBreaches = dataBreaches;
        }
        
        public double getEncryptionCoverage() {
            return encryptionCoverage;
        }
        
        public void setEncryptionCoverage(double encryptionCoverage) {
            this.encryptionCoverage = encryptionCoverage;
        }
        
        public int getFailedAuthAttempts() {
            return failedAuthAttempts;
        }
        
        public void setFailedAuthAttempts(int failedAuthAttempts) {
            this.failedAuthAttempts = failedAuthAttempts;
        }
        
        public Map<String, String> getSecurityControls() {
            return securityControls;
        }
        
        public void setSecurityControls(Map<String, String> securityControls) {
            this.securityControls = securityControls;
        }
    }
    
    /**
     * Data privacy compliance metrics.
     */
    @Schema(description = "Data privacy and GDPR compliance metrics")
    public static class DataPrivacyCompliance {
        private boolean gdprCompliant;
        private int dataRequestsProcessed;
        private int dataRetentionViolations;
        private int consentViolations;
        private double dataMinimizationScore;
        private Map<String, String> privacyControls;
        
        // Constructors
        public DataPrivacyCompliance() {}
        
        // Getters and Setters
        public boolean isGdprCompliant() {
            return gdprCompliant;
        }
        
        public void setGdprCompliant(boolean gdprCompliant) {
            this.gdprCompliant = gdprCompliant;
        }
        
        public int getDataRequestsProcessed() {
            return dataRequestsProcessed;
        }
        
        public void setDataRequestsProcessed(int dataRequestsProcessed) {
            this.dataRequestsProcessed = dataRequestsProcessed;
        }
        
        public int getDataRetentionViolations() {
            return dataRetentionViolations;
        }
        
        public void setDataRetentionViolations(int dataRetentionViolations) {
            this.dataRetentionViolations = dataRetentionViolations;
        }
        
        public int getConsentViolations() {
            return consentViolations;
        }
        
        public void setConsentViolations(int consentViolations) {
            this.consentViolations = consentViolations;
        }
        
        public double getDataMinimizationScore() {
            return dataMinimizationScore;
        }
        
        public void setDataMinimizationScore(double dataMinimizationScore) {
            this.dataMinimizationScore = dataMinimizationScore;
        }
        
        public Map<String, String> getPrivacyControls() {
            return privacyControls;
        }
        
        public void setPrivacyControls(Map<String, String> privacyControls) {
            this.privacyControls = privacyControls;
        }
    }
    
    /**
     * Risk assessment details.
     */
    @Schema(description = "Operational risk assessment")
    public static class RiskAssessment {
        private String riskCategory;
        private String riskLevel;
        private String description;
        private double probability;
        private double impact;
        private String mitigationStatus;
        private ZonedDateTime assessmentDate;
        
        // Constructors
        public RiskAssessment() {}
        
        // Getters and Setters
        public String getRiskCategory() {
            return riskCategory;
        }
        
        public void setRiskCategory(String riskCategory) {
            this.riskCategory = riskCategory;
        }
        
        public String getRiskLevel() {
            return riskLevel;
        }
        
        public void setRiskLevel(String riskLevel) {
            this.riskLevel = riskLevel;
        }
        
        public String getDescription() {
            return description;
        }
        
        public void setDescription(String description) {
            this.description = description;
        }
        
        public double getProbability() {
            return probability;
        }
        
        public void setProbability(double probability) {
            this.probability = probability;
        }
        
        public double getImpact() {
            return impact;
        }
        
        public void setImpact(double impact) {
            this.impact = impact;
        }
        
        public String getMitigationStatus() {
            return mitigationStatus;
        }
        
        public void setMitigationStatus(String mitigationStatus) {
            this.mitigationStatus = mitigationStatus;
        }
        
        public ZonedDateTime getAssessmentDate() {
            return assessmentDate;
        }
        
        public void setAssessmentDate(ZonedDateTime assessmentDate) {
            this.assessmentDate = assessmentDate;
        }
    }
    
    /**
     * Compliance violation details.
     */
    @Schema(description = "Compliance violation or issue")
    public static class ComplianceViolation {
        private String violationType;
        private String severity;
        private String description;
        private ZonedDateTime detectedAt;
        private String status;
        private String remediation;
        private ZonedDateTime dueDate;
        
        // Constructors
        public ComplianceViolation() {}
        
        // Getters and Setters
        public String getViolationType() {
            return violationType;
        }
        
        public void setViolationType(String violationType) {
            this.violationType = violationType;
        }
        
        public String getSeverity() {
            return severity;
        }
        
        public void setSeverity(String severity) {
            this.severity = severity;
        }
        
        public String getDescription() {
            return description;
        }
        
        public void setDescription(String description) {
            this.description = description;
        }
        
        public ZonedDateTime getDetectedAt() {
            return detectedAt;
        }
        
        public void setDetectedAt(ZonedDateTime detectedAt) {
            this.detectedAt = detectedAt;
        }
        
        public String getStatus() {
            return status;
        }
        
        public void setStatus(String status) {
            this.status = status;
        }
        
        public String getRemediation() {
            return remediation;
        }
        
        public void setRemediation(String remediation) {
            this.remediation = remediation;
        }
        
        public ZonedDateTime getDueDate() {
            return dueDate;
        }
        
        public void setDueDate(ZonedDateTime dueDate) {
            this.dueDate = dueDate;
        }
    }
}
