apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-gateway-backup
  labels:
    app: payment-gateway
    component: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-gateway-backup
  labels:
    app: payment-gateway
    component: backup
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: payment-gateway-backup
  labels:
    app: payment-gateway
    component: backup
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payment-gateway-backup
  labels:
    app: payment-gateway
    component: backup
subjects:
- kind: ServiceAccount
  name: payment-gateway-backup
roleRef:
  kind: Role
  name: payment-gateway-backup
  apiGroup: rbac.authorization.k8s.io
---
# Secret template for backup configuration
apiVersion: v1
kind: Secret
metadata:
  name: payment-gateway-backup
  labels:
    app: payment-gateway
    component: backup
type: Opaque
stringData:
  s3-bucket: "payment-gateway-backups"
  aws-access-key-id: "AKIA..."  # Replace with actual AWS access key
  aws-secret-access-key: "..."  # Replace with actual AWS secret key
  backup-encryption-key: "..."  # Optional: encryption key for backups
